### ISSUE TITLE
Is it usable?

### ISSUE THREAD

**Issue by Gnaj** [victorst79/Riot-Live-Stats#16]
Hello i'm really interested in this kind of software for my personal stream, i tried to get it to work but i failed, is it ready to be tested/used??

**Comment by victorst79** [comment]
Hi @Gnaj,

This project started as an open source product for streams with statistics in real time, but the project was paralyzed some time ago due to lack of investment and time.
I'm sorry to tell you currently there are no future plans to resume the project.

Regards.
